stages:
  - build
  - deploy

builder:
  stage: build
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind
  script:
    - docker build -t local_build:latest .
  except:
    - main

deployer:
  stage: deploy
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/evgeni-listopad/netology-example .
    - docker push registry.gitlab.com/evgeni-listopad/netology-example 
  only:
    - main
