---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-2
  labels:
    app: pvc-2
spec:
  storageClassName: sc-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
