---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: cetnos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - create
    - converge
    - destroy
