{
 "title": "Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{cpu=\"0\", job=\"nodeexporter\", mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "CPU_core0"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{cpu=\"1\", job=\"nodeexporter\", mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "CPU_core1"
    }
   ]
  },
  {
   "title": "CPU load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU_la_1" },
    { "expr": "node_load5", "legendFormat": "CPU_la_5" },
    { "expr": "node_load15", "legendFormat": "CPU_la_15" }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Memory total" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Memory free" }
   ]
  },
  {
   "title": "Root file system free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"}",
     "legendFormat": "Root file system free space"
    }
   ]
  }
 ]
}