---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse
  - src: git@github.com:evgeni-listopad/vector-role.git
    scm: git
    version: "0.25.1"
    name: vector-role
  - src: git@github.com:evgeni-listopad/lighthouse-role.git
    scm: git
    version: "1.1.1" 
